# Generated by Django 5.2.14 on 2026-05-26 22:19

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_type', models.SlugField(max_length=64, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('specialty', models.CharField(db_index=True, default='urology', max_length=64)),
                ('summary', models.TextField(blank=True)),
                ('anatomy_focus', models.JSONField(blank=True, default=list)),
                ('decision_points', models.JSONField(blank=True, default=list)),
                ('complication_patterns', models.JSONField(blank=True, default=list)),
                ('attending_question_categories', models.JSONField(blank=True, default=list)),
                ('patient_factor_fields', models.JSONField(blank=True, default=list)),
                ('review_status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=32)),
                ('version', models.CharField(default='0.0.0', max_length=32)),
                ('last_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_case_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('specialty', 'case_type'),
            },
        ),
        migrations.CreateModel(
            name='HistoricalCaseTemplate',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('case_type', models.SlugField(max_length=64)),
                ('title', models.CharField(max_length=255)),
                ('specialty', models.CharField(db_index=True, default='urology', max_length=64)),
                ('summary', models.TextField(blank=True)),
                ('anatomy_focus', models.JSONField(blank=True, default=list)),
                ('decision_points', models.JSONField(blank=True, default=list)),
                ('complication_patterns', models.JSONField(blank=True, default=list)),
                ('attending_question_categories', models.JSONField(blank=True, default=list)),
                ('patient_factor_fields', models.JSONField(blank=True, default=list)),
                ('review_status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=32)),
                ('version', models.CharField(default='0.0.0', max_length=32)),
                ('last_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical case template',
                'verbose_name_plural': 'historical case templates',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalSurgeonPreference',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('preferences', models.JSONField(blank=True, default=list)),
                ('review_status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=32)),
                ('version', models.CharField(default='0.0.0', max_length=32)),
                ('last_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('case_template', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cases.casetemplate')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('surgeon', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical surgeon preference',
                'verbose_name_plural': 'historical surgeon preferences',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='SurgeonPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferences', models.JSONField(blank=True, default=list)),
                ('review_status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=32)),
                ('version', models.CharField(default='0.0.0', max_length=32)),
                ('last_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surgeon_preferences', to='cases.casetemplate')),
                ('surgeon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='surgeon_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('case_template', 'surgeon'),
                'unique_together': {('case_template', 'surgeon')},
            },
        ),
    ]
