# Generated by Django 5.2.14 on 2026-05-28 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='casetemplate',
            name='briefing_model_override',
            field=models.CharField(blank=True, help_text='Optional. Model name for the override provider. If blank, uses LLM_BRIEFING_MODEL from settings.', max_length=128),
        ),
        migrations.AddField(
            model_name='casetemplate',
            name='briefing_provider_override',
            field=models.CharField(blank=True, help_text='Optional. One of: anthropic, openai, lmstudio, openrouter. If blank, uses LLM_BRIEFING_PROVIDER from settings.', max_length=32),
        ),
        migrations.AddField(
            model_name='historicalcasetemplate',
            name='briefing_model_override',
            field=models.CharField(blank=True, help_text='Optional. Model name for the override provider. If blank, uses LLM_BRIEFING_MODEL from settings.', max_length=128),
        ),
        migrations.AddField(
            model_name='historicalcasetemplate',
            name='briefing_provider_override',
            field=models.CharField(blank=True, help_text='Optional. One of: anthropic, openai, lmstudio, openrouter. If blank, uses LLM_BRIEFING_PROVIDER from settings.', max_length=32),
        ),
    ]
