# Generated by Django 5.2.14 on 2026-05-28 22:02

import apps.cases.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_casetemplate_briefing_model_override_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casetemplate',
            name='patient_factor_fields',
        ),
        migrations.RemoveField(
            model_name='historicalcasetemplate',
            name='patient_factor_fields',
        ),
        migrations.AddField(
            model_name='casetemplate',
            name='input_schema',
            field=models.JSONField(blank=True, default=apps.cases.models._default_input_schema),
        ),
        migrations.AddField(
            model_name='historicalcasetemplate',
            name='input_schema',
            field=models.JSONField(blank=True, default=apps.cases.models._default_input_schema),
        ),
    ]
