# Generated by Django 5.2.14 on 2026-05-26 22:19

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
        ('documents', '0002_alter_document_unique_together_and_more'),
        ('modules', '0001_initial'),
        ('wiki', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_id', models.SlugField(max_length=128)),
                ('statement', models.TextField()),
                ('source_quote', models.TextField(blank=True, help_text='Exact text span from the source supporting the statement.')),
                ('source_locator', models.JSONField(blank=True, default=dict)),
                ('audit_status', models.CharField(choices=[('proposed', 'Proposed (pre-audit)'), ('audited_ok', 'Audit OK'), ('audited_weak', 'Audit flagged weak'), ('published', 'Published'), ('rejected', 'Rejected')], default='proposed', max_length=32)),
                ('audit_notes', models.TextField(blank=True, help_text='Adversarial-audit verdict and rationale (LLM- or faculty-written).')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('wiki_page', 'claim_id'),
            },
        ),
        migrations.CreateModel(
            name='HistoricalClaim',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('claim_id', models.SlugField(max_length=128)),
                ('statement', models.TextField()),
                ('source_quote', models.TextField(blank=True, help_text='Exact text span from the source supporting the statement.')),
                ('source_locator', models.JSONField(blank=True, default=dict)),
                ('audit_status', models.CharField(choices=[('proposed', 'Proposed (pre-audit)'), ('audited_ok', 'Audit OK'), ('audited_weak', 'Audit flagged weak'), ('published', 'Published'), ('rejected', 'Rejected')], default='proposed', max_length=32)),
                ('audit_notes', models.TextField(blank=True, help_text='Adversarial-audit verdict and rationale (LLM- or faculty-written).')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical claim',
                'verbose_name_plural': 'historical claims',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AlterModelOptions(
            name='wikipage',
            options={'ordering': ('path',)},
        ),
        migrations.AlterUniqueTogether(
            name='wikipage',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='historicalwikipage',
            name='case_template',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cases.casetemplate'),
        ),
        migrations.AddField(
            model_name='wikipage',
            name='case_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wiki_pages', to='cases.casetemplate'),
        ),
        migrations.AlterField(
            model_name='wikipage',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wiki_pages', to='modules.module'),
        ),
        migrations.AddConstraint(
            model_name='wikipage',
            constraint=models.UniqueConstraint(condition=models.Q(('module__isnull', False)), fields=('module', 'path'), name='wiki_unique_module_path'),
        ),
        migrations.AddConstraint(
            model_name='wikipage',
            constraint=models.UniqueConstraint(condition=models.Q(('case_template__isnull', False)), fields=('case_template', 'path'), name='wiki_unique_case_template_path'),
        ),
        migrations.AddConstraint(
            model_name='wikipage',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('case_template__isnull', True), ('module__isnull', False)), models.Q(('case_template__isnull', False), ('module__isnull', True)), _connector='OR'), name='wiki_one_parent_only'),
        ),
        migrations.AddField(
            model_name='claim',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_claims', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='claim',
            name='source_document',
            field=models.ForeignKey(blank=True, help_text="The source from which this claim was extracted. May be null for documented personal preferences (e.g., a surgeon's noted approach).", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='claims', to='documents.document'),
        ),
        migrations.AddField(
            model_name='claim',
            name='wiki_page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='wiki.wikipage'),
        ),
        migrations.AddField(
            model_name='historicalclaim',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalclaim',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalclaim',
            name='source_document',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text="The source from which this claim was extracted. May be null for documented personal preferences (e.g., a surgeon's noted approach).", null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='documents.document'),
        ),
        migrations.AddField(
            model_name='historicalclaim',
            name='wiki_page',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='wiki.wikipage'),
        ),
        migrations.AlterUniqueTogether(
            name='claim',
            unique_together={('wiki_page', 'claim_id')},
        ),
    ]
