# Generated by Django 5.2.14 on 2026-05-27 02:46

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_alter_document_unique_together_and_more'),
        ('wiki', '0002_claim_historicalclaim_alter_wikipage_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalIngestRun',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('model_propose', models.CharField(blank=True, max_length=64)),
                ('model_audit', models.CharField(blank=True, max_length=64)),
                ('model_compose', models.CharField(blank=True, max_length=64)),
                ('propose_tokens_in', models.IntegerField(default=0)),
                ('propose_tokens_out', models.IntegerField(default=0)),
                ('audit_tokens_in', models.IntegerField(default=0)),
                ('audit_tokens_out', models.IntegerField(default=0)),
                ('compose_tokens_in', models.IntegerField(default=0)),
                ('compose_tokens_out', models.IntegerField(default=0)),
                ('cost_usd', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('claims_proposed', models.IntegerField(default=0)),
                ('claims_audited_ok', models.IntegerField(default=0)),
                ('claims_audited_weak', models.IntegerField(default=0)),
                ('claims_created', models.IntegerField(default=0)),
                ('claims_updated', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='running', max_length=32)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, editable=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('ingested_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('source_document', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='documents.document')),
            ],
            options={
                'verbose_name': 'historical ingest run',
                'verbose_name_plural': 'historical ingest runs',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='IngestRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_propose', models.CharField(blank=True, max_length=64)),
                ('model_audit', models.CharField(blank=True, max_length=64)),
                ('model_compose', models.CharField(blank=True, max_length=64)),
                ('propose_tokens_in', models.IntegerField(default=0)),
                ('propose_tokens_out', models.IntegerField(default=0)),
                ('audit_tokens_in', models.IntegerField(default=0)),
                ('audit_tokens_out', models.IntegerField(default=0)),
                ('compose_tokens_in', models.IntegerField(default=0)),
                ('compose_tokens_out', models.IntegerField(default=0)),
                ('cost_usd', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('claims_proposed', models.IntegerField(default=0)),
                ('claims_audited_ok', models.IntegerField(default=0)),
                ('claims_audited_weak', models.IntegerField(default=0)),
                ('claims_created', models.IntegerField(default=0)),
                ('claims_updated', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='running', max_length=32)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('ingested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ingest_runs', to=settings.AUTH_USER_MODEL)),
                ('source_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingest_runs', to='documents.document')),
                ('wiki_pages', models.ManyToManyField(blank=True, related_name='ingest_runs', to='wiki.wikipage')),
            ],
            options={
                'ordering': ('-started_at',),
            },
        ),
    ]
