# Generated by Django 5.2.14 on 2026-05-28 00:58

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0003_historicalingestrun_ingestrun'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalLLMSettings',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('briefing_provider', models.CharField(blank=True, max_length=32)),
                ('briefing_model', models.CharField(blank=True, max_length=128)),
                ('ingest_propose_provider', models.CharField(blank=True, max_length=32)),
                ('ingest_propose_model', models.CharField(blank=True, max_length=128)),
                ('ingest_audit_provider', models.CharField(blank=True, max_length=32)),
                ('ingest_audit_model', models.CharField(blank=True, max_length=128)),
                ('ingest_compose_provider', models.CharField(blank=True, max_length=32)),
                ('ingest_compose_model', models.CharField(blank=True, max_length=128)),
                ('anthropic_api_key_enc', models.TextField(blank=True)),
                ('openai_api_key_enc', models.TextField(blank=True)),
                ('openrouter_api_key_enc', models.TextField(blank=True)),
                ('lmstudio_api_key_enc', models.TextField(blank=True)),
                ('openai_base_url', models.CharField(blank=True, max_length=255)),
                ('lmstudio_base_url', models.CharField(blank=True, max_length=255)),
                ('openrouter_base_url', models.CharField(blank=True, max_length=255)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical LLM settings',
                'verbose_name_plural': 'historical LLM settings',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='LLMSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('briefing_provider', models.CharField(blank=True, max_length=32)),
                ('briefing_model', models.CharField(blank=True, max_length=128)),
                ('ingest_propose_provider', models.CharField(blank=True, max_length=32)),
                ('ingest_propose_model', models.CharField(blank=True, max_length=128)),
                ('ingest_audit_provider', models.CharField(blank=True, max_length=32)),
                ('ingest_audit_model', models.CharField(blank=True, max_length=128)),
                ('ingest_compose_provider', models.CharField(blank=True, max_length=32)),
                ('ingest_compose_model', models.CharField(blank=True, max_length=128)),
                ('anthropic_api_key_enc', models.TextField(blank=True)),
                ('openai_api_key_enc', models.TextField(blank=True)),
                ('openrouter_api_key_enc', models.TextField(blank=True)),
                ('lmstudio_api_key_enc', models.TextField(blank=True)),
                ('openai_base_url', models.CharField(blank=True, max_length=255)),
                ('lmstudio_base_url', models.CharField(blank=True, max_length=255)),
                ('openrouter_base_url', models.CharField(blank=True, max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_llm_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'LLM settings',
                'verbose_name_plural': 'LLM settings',
            },
        ),
    ]
