# Generated by Django 5.2.14 on 2026-05-26 22:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
        ('documents', '0001_initial'),
        ('modules', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='document',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='document',
            name='case_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='cases.casetemplate'),
        ),
        migrations.AddField(
            model_name='document',
            name='citation',
            field=models.TextField(blank=True, help_text='Human-readable citation string (author, title, journal/publisher, year).'),
        ),
        migrations.AddField(
            model_name='document',
            name='last_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='review_status',
            field=models.CharField(choices=[('unreviewed', 'Unreviewed'), ('published', 'Published (claims may be cited)'), ('archived', 'Archived (not citable)')], default='unreviewed', max_length=32),
        ),
        migrations.AddField(
            model_name='document',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='document',
            name='source_date',
            field=models.CharField(blank=True, help_text='Publication / version date of the source (free-form: YYYY, YYYY-MM, YYYY-MM-DD).', max_length=64),
        ),
        migrations.AddField(
            model_name='historicaldocument',
            name='case_template',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cases.casetemplate'),
        ),
        migrations.AddField(
            model_name='historicaldocument',
            name='citation',
            field=models.TextField(blank=True, help_text='Human-readable citation string (author, title, journal/publisher, year).'),
        ),
        migrations.AddField(
            model_name='historicaldocument',
            name='last_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicaldocument',
            name='review_status',
            field=models.CharField(choices=[('unreviewed', 'Unreviewed'), ('published', 'Published (claims may be cited)'), ('archived', 'Archived (not citable)')], default='unreviewed', max_length=32),
        ),
        migrations.AddField(
            model_name='historicaldocument',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaldocument',
            name='source_date',
            field=models.CharField(blank=True, help_text='Publication / version date of the source (free-form: YYYY, YYYY-MM, YYYY-MM-DD).', max_length=64),
        ),
        migrations.AlterField(
            model_name='document',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='modules.module'),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.UniqueConstraint(condition=models.Q(('module__isnull', False)), fields=('module', 'sha256'), name='documents_unique_module_sha'),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.UniqueConstraint(condition=models.Q(('case_template__isnull', False)), fields=('case_template', 'sha256'), name='documents_unique_case_template_sha'),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('case_template__isnull', True), ('module__isnull', False)), models.Q(('case_template__isnull', False), ('module__isnull', True)), _connector='OR'), name='documents_one_parent_only'),
        ),
    ]
