# Generated by Django 5.2.14 on 2026-05-25 23:39

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_id', models.SlugField(max_length=128, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('curriculum', models.CharField(db_index=True, max_length=64)),
                ('specialty', models.CharField(blank=True, db_index=True, max_length=64)),
                ('learner_level', models.CharField(blank=True, max_length=64)),
                ('estimated_minutes', models.PositiveIntegerField(default=0)),
                ('module_type', models.CharField(choices=[('clinical_reasoning', 'Clinical reasoning'), ('ethics', 'Ethics'), ('board_review', 'Board review'), ('procedural', 'Procedural'), ('communication', 'Communication'), ('mixed', 'Mixed')], default='mixed', max_length=32)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('faculty_reviewed', 'Faculty reviewed'), ('pilot_ready', 'Pilot ready'), ('active', 'Active'), ('retired', 'Retired')], default='draft', max_length=32)),
                ('version', models.CharField(default='0.0.0', max_length=32)),
                ('source_version_date', models.CharField(blank=True, max_length=64)),
                ('activities', models.JSONField(blank=True, default=list)),
                ('cases', models.JSONField(blank=True, default=list)),
                ('remediation_paths', models.JSONField(blank=True, default=list)),
                ('faculty_review', models.JSONField(blank=True, default=dict)),
                ('yaml_path', models.CharField(blank=True, max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('curriculum', 'title'),
            },
        ),
        migrations.CreateModel(
            name='HistoricalModule',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('module_id', models.SlugField(max_length=128)),
                ('title', models.CharField(max_length=255)),
                ('curriculum', models.CharField(db_index=True, max_length=64)),
                ('specialty', models.CharField(blank=True, db_index=True, max_length=64)),
                ('learner_level', models.CharField(blank=True, max_length=64)),
                ('estimated_minutes', models.PositiveIntegerField(default=0)),
                ('module_type', models.CharField(choices=[('clinical_reasoning', 'Clinical reasoning'), ('ethics', 'Ethics'), ('board_review', 'Board review'), ('procedural', 'Procedural'), ('communication', 'Communication'), ('mixed', 'Mixed')], default='mixed', max_length=32)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('faculty_reviewed', 'Faculty reviewed'), ('pilot_ready', 'Pilot ready'), ('active', 'Active'), ('retired', 'Retired')], default='draft', max_length=32)),
                ('version', models.CharField(default='0.0.0', max_length=32)),
                ('source_version_date', models.CharField(blank=True, max_length=64)),
                ('activities', models.JSONField(blank=True, default=list)),
                ('cases', models.JSONField(blank=True, default=list)),
                ('remediation_paths', models.JSONField(blank=True, default=list)),
                ('faculty_review', models.JSONField(blank=True, default=dict)),
                ('yaml_path', models.CharField(blank=True, max_length=512)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical module',
                'verbose_name_plural': 'historical modules',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='LearningObjective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objective_id', models.SlugField(max_length=128)),
                ('text', models.TextField()),
                ('domain', models.CharField(choices=[('knowledge', 'Knowledge'), ('reasoning', 'Reasoning'), ('communication', 'Communication'), ('ethics', 'Ethics'), ('procedural', 'Procedural')], default='reasoning', max_length=32)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_objectives', to='modules.module')),
            ],
            options={
                'ordering': ('module', 'objective_id'),
                'unique_together': {('module', 'objective_id')},
            },
        ),
        migrations.CreateModel(
            name='HistoricalReference',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('ref_id', models.SlugField(max_length=128)),
                ('title', models.TextField()),
                ('url', models.CharField(blank=True, max_length=512)),
                ('version_date', models.CharField(blank=True, max_length=64)),
                ('approved_by', models.CharField(blank=True, max_length=128)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('module', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='modules.module')),
            ],
            options={
                'verbose_name': 'historical reference',
                'verbose_name_plural': 'historical references',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalLearningObjective',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('objective_id', models.SlugField(max_length=128)),
                ('text', models.TextField()),
                ('domain', models.CharField(choices=[('knowledge', 'Knowledge'), ('reasoning', 'Reasoning'), ('communication', 'Communication'), ('ethics', 'Ethics'), ('procedural', 'Procedural')], default='reasoning', max_length=32)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('module', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='modules.module')),
            ],
            options={
                'verbose_name': 'historical learning objective',
                'verbose_name_plural': 'historical learning objectives',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalKnowledgeCheck',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('check_id', models.SlugField(max_length=128)),
                ('question', models.TextField()),
                ('options', models.JSONField(default=list)),
                ('correct_option_id', models.CharField(max_length=32)),
                ('explanation', models.TextField(blank=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('module', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='modules.module')),
            ],
            options={
                'verbose_name': 'historical knowledge check',
                'verbose_name_plural': 'historical knowledge checks',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='KnowledgeCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_id', models.SlugField(max_length=128)),
                ('question', models.TextField()),
                ('options', models.JSONField(default=list)),
                ('correct_option_id', models.CharField(max_length=32)),
                ('explanation', models.TextField(blank=True)),
                ('objectives', models.ManyToManyField(blank=True, related_name='knowledge_checks', to='modules.learningobjective')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_checks', to='modules.module')),
            ],
            options={
                'ordering': ('module', 'check_id'),
                'unique_together': {('module', 'check_id')},
            },
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_id', models.SlugField(max_length=128)),
                ('title', models.TextField()),
                ('url', models.CharField(blank=True, max_length=512)),
                ('version_date', models.CharField(blank=True, max_length=64)),
                ('approved_by', models.CharField(blank=True, max_length=128)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='modules.module')),
            ],
            options={
                'ordering': ('module', 'ref_id'),
                'unique_together': {('module', 'ref_id')},
            },
        ),
    ]
